### ISSUE TITLE
Transfer repo to PrismarineJS ?

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/McDataExtracting#2]
Hi,
We're considering using this repo for extracting more things for minecraft data.
What do you think about transferring it to PrismarineJS org so it's easier for maintenance ?

**Comment by Gjum** [comment]
That's fine by me, it's too much effort for me to maintain but it looks like others have some use for it (PrismarineMC/mcdata, #1). Seems like I can't transfer it yet, so message me once you've set up the [necessary permissions](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository):

> To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization.

**Comment by rom1504** [comment]
Sent you an invite. After you accept it, you should be able to transfer
